name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:

jobs:

  # linter job
    lint:
    name: Lint (black + isort + flake8)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 flake8-bugbear

      - name: Run Black (check)
        run: |
          black --check \
            --exclude="(venv|env|migrations)" .

      - name: Run isort (check)
        run: |
          isort --profile black --check-only \
            --skip venv --skip env --skip migrations .

      - name: Run flake8
        run: |
          flake8 \
            --exclude=venv,env,migrations


  # test job
  tests:
    name: Tests + Coverage
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: pytest --cov=src --cov-report=xml --cov-report=term-missing

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml


  # deploy job
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: tests   # deploy only if tests pass
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"


  # health check job
  healthcheck:
    name: Health Check on Render
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Wait for Render healthcheck
        run: |
          echo "Waiting for production health..."
          for i in {1..40}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://hpk-lab.onrender.com/common/healthcheck || true)
            if [ "$STATUS" = "200" ]; then
              echo "Service is healthy!"
              exit 0
            fi
            echo "Still waiting... ($i/40)"
            sleep 10
          done
          echo "Service did not pass healthcheck"
          exit 1
